# Generated by Django 3.1.3 on 2021-04-15 05:30

import core.upload_rename
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=core.upload_rename.wrapper)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('model_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('soon', 'Soon')], default='soon', max_length=4)),
                ('car_type', models.CharField(choices=[('Автомобиль', 'Auto')], default='Автомобиль', max_length=50)),
                ('gearbox', models.CharField(choices=[('Автоматический', 'Auto')], default='Автоматический', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(to='cars.CustomImageModel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
